#!/usr/bin/env bash
set -euo pipefail

# shellcheck source=image/setup/common
source "$(dirname -- "${BASH_SOURCE[0]}")/../common"

echo "==> Gaming stack"
dnf5 -y --setopt=install_weak_deps=False install \
  steam \
  steam-devices \
  lutris

dnf5 install -y \
  mangohud.x86_64 \
  mangohud.i686 \
  gamescope \
  vkBasalt.x86_64 \
  vkBasalt.i686

retry curl -fsSL --retry 3 \
  -o /usr/bin/winetricks \
  https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
chmod +x /usr/bin/winetricks
