[General]
showlogo=shown
showClock=true
logo=/usr/share/sddm/themes/bluecat-breeze/bluecat-logo.png
type=image
color=#006fb3
fontSize=10
background=/usr/share/backgrounds/default.jxl
needsFullUserModel=false
