# Anaconda configuration file for bluecat.

[Profile]
profile_id = bluecat
base_profile = fedora

[Profile Detection]
os_id = bluecat

[Network]
default_on_boot = FIRST_WIRED_WITH_LINK

[Bootloader]
efi_dir = fedora
menu_auto_hide = True

[Storage]
default_scheme = BTRFS
btrfs_compression = zstd:1
default_partitioning =
    /     (min 1 GiB, max 70 GiB)
    /home (min 500 MiB)

[User Interface]
hidden_spokes =
    NetworkSpoke
    PasswordSpoke
    UserSpoke
# Live spin default browser for the Web UI.
webui_web_engine = slitherer
hidden_webui_pages =
    anaconda-screen-accounts
    anaconda-screen-network

[Localization]
use_geolocation = False
