# Anaconda configuration file for bluecat.

[Profile]
profile_id = bluecat
base_profile = fedora

[Profile Detection]
os_id = bluecat

[Network]
default_on_boot = FIRST_WIRED_WITH_LINK

[Bootloader]
efi_dir = fedora
menu_auto_hide = True

[Storage]
default_scheme = BTRFS
btrfs_compression = zstd:1
default_partitioning =
    /     (min 1 GiB, max 70 GiB)
    swap

[User Interface]
hidden_webui_pages =
    network

[Localization]
use_geolocation = False